/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "sa-east-1",
    "aws_cognito_identity_pool_id": "sa-east-1:0dbf0d78-bc30-49b6-a623-c04a265be8a7",
    "aws_cognito_region": "sa-east-1",
    "aws_user_pools_id": "sa-east-1_EcUkM0iSe",
    "aws_user_pools_web_client_id": "6he3hg6hglt5tlq0uvm5frd2nc",
    "oauth": {
        "domain": "mockwyzrdc62088c-dc62088c-dev.auth.sa-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/,https://dev.d3gsg7noo9b6v6.amplifyapp.com/",
        "redirectSignOut": "http://localhost:3000/,https://dev.d3gsg7noo9b6v6.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "sa-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "usersTable-dev",
            "region": "sa-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "userInfo",
            "endpoint": "https://yk1r3bpak2.execute-api.sa-east-1.amazonaws.com/dev",
            "region": "sa-east-1"
        }
    ]
};


export default awsmobile;
